apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-config
  namespace: mc-dev
  labels:
    app: minecraft
data:
  EULA: "TRUE"
  TYPE: "PAPER"
  VERSION: "1.20.6"
  MEMORY: "2G"
  MOTD: "OpenShift Minecraft \u2764"