apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-dev
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/itzg/minecraft-server
    newTag: latest