apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-world
  namespace: mc-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: gp2-csi   # ← set for your cluster